### ISSUE TITLE
Non in-game items reported to EDDN

### ISSUE THREAD

**Issue by maddavo** [nomadyow/Ocellus#6]
Hi, I run an EDDN receiver and have been monitoring some messages with items that do not appear in-game.  Only in-game items should be published to EDDN.

ED Assistant 0.95 reports "Drones" - I imagine this is because "Drones" do appear in the companion API response but they are not an item that appears in the in-game markets or that can be traded.  ED Assistant needs to filter out this item and not transmit it to EDDN.

Also there is "Heliostatic Furnaces" from the API - but in-game these are called "Microbial Furnaces".  ED Assistant should have a translation table that gets the name of an item from the API and translates it to the in-game name and then publishes the in-game name to EDDN.

Cheers,
Maddavo

**Comment by maddavo** [comment]
"Atmospheric Extractors" (API) should be "Atmospheric Processors" (in-game)

**Comment by maddavo** [comment]
Here is an example translation table from API to in-game items from another API-to-EDDN tool.
    'Agricultural Medicines': 'Agri-Medicines',
    'Animalmeat': 'Animal Meat',
    'Atmospheric Extractors': 'Atmospheric Processors',
    'Auto Fabricators': 'Auto-Fabricators',
    'Basic Narcotics': 'Narcotics',
    'Bio Reducing Lichen': 'Bioreducing Lichen',
    'C M M Composite': 'CMM Composite',
    'Comercial Samples': 'Commercial Samples',
    'Diagnostic Sensor': 'Hardware Diagnostic Sensor',
    'Encripted Data Storage': 'Encrypted Data Storage',
    'H N Shock Mount': 'HN Shock Mount',
    'Hafnium178': 'Hafnium 178',
    'Hazardous Environment Suits': 'H.E. Suits',
    'Heliostatic Furnaces': 'Microbial Furnaces',
    'Marine Supplies': 'Marine Equipment',
    'Meta Alloys': 'Meta-Alloys',
    'Methanol Monohydrate Crystals': 'Methanol Monohydrate',
    'Mu Tom Imager': 'Muon Imager',
    'Non Lethal Weapons': 'Non-Lethal Weapons',
    'Power Grid Assembly': 'Energy Grid Assembly',
    'Power Transfer Conduits': 'Power Transfer Bus',
    'S A P8 Core Container': 'SAP 8 Core Container',
    'Skimer Components': 'Skimmer Components',
    'Terrain Enrichment Systems': 'Land Enrichment Systems',
    'Trinkets Of Fortune': 'Trinkets Of Hidden Fortune',
    'Unknown Artifact': 'Unknown Artefact',
    'U S S Cargo Ancient Artefact': 'Ancient Artefact',
    'U S S Cargo Experimental Chemicals': 'Experimental Chemicals',
    'U S S Cargo Military Plans': 'Military Plans',
    'U S S Cargo Prototype Tech': 'Prototype Tech',
    'U S S Cargo Rebel Transmissions': 'Rebel Transmissions',
    'U S S Cargo Technical Blueprints': 'Technical Blueprints',
    'U S S Cargo Trade Data': 'Trade Data',
    'Wreckage Components': 'Salvageable Wreckage',

**Comment by maddavo** [comment]
Hi, this tool is still reporting "Drones" - do you think you could look into that?

**Comment by damonbrodie** [comment]
looking at this now.

**Comment by damonbrodie** [comment]
I've used the same translation table as EDMC and fixed this in 0.96

**Comment by maddavo** [comment]
The item "Limpet" is being reported by this tool to EDDN but it is not in the in-game market.  This is the same item as "Drones" but renamed.  The API reports the item when you can restock the item but it is not a commodity item.  Please remove it from being reported to EDDN.  It is being reported by v0.96 clients.
